apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-ingress-certificate
  namespace: media
spec:
  secretName: radarr-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - radarr.k3s.ravenholm.io