apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: radarr-config-volume
    namespace: media
    labels:
      app: radarr
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 5Gi