apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # type of authentication
    traefik.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    traefik.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    traefik.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    traefik.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    traefik.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: traefik
  rules:
    - host: radarr.k3s.ravenholm.io
      http:
        paths:
          - path: /
            pathType: Prefix
            service:
              name: radarr
              port:
                number: 80
  tls:
    - secretName: radarr-certificate-secret