apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      navidrome:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.55.2@sha256:3a66e262b7ea836faa06c08ad5b32076c49e9e63e2fa4de10080c8e9be9f0846
            env:
              ND_DATAFOLDER: /config
              ND_LOGLEVEL: info
              ND_SCANSCHEDULE: "@every 1h"
              ND_SESSIONTIMEOUT: 24h
              ND_MUSICFOLDER: /music
            envFrom:
              - secretRef:
                  name: navidrome-secrets
            resources:
              requests:
                cpu: 200m
                memory: 500Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: navidrome
        ports:
          http:
            port: 4533
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: navidrome.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - navidrome.${DOMAIN}
            secretName: navidrome-certificate-secret
    persistence:
      config:
        enabled: true
        existingClaim: navidrome-config-volume
      music:
        type: nfs
        server: 10.0.0.20
        path: /mnt/zpool2/audio
        globalMounts:
          - path: /music
