apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      navidrome:
        containers:
          app:
            image:
              repository: deluan/navidrome
              tag: 0.55.2
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 4533
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 200m
                memory: 500Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: navidrome
        ports:
          http:
            port: *port
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: navidrome.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - navidrome.k3s.ravenholm.io
            secretName: navidrome-certificate-secret
    persistence:
      config:
        enabled: true
        existingClaim: navidrome-config-volume
        mountPath: /data
      music:
        type: nfs
        server: 10.0.0.20
        path: /mnt/zpool2/audio
        globalMounts:
          - path: /music
