apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sabnzbd-config-volume
    namespace: media
    labels:
      app: sabnzbd
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 5Gi