apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: zwave-js-ui-config-volume
    namespace: home
    labels:
      app: zwave-js-ui
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi