apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zwave-js-ui
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      zwave-js-ui:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            zooz.feature.node.kubernetes.io/zwave: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 10.6.1
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8091
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
    service:
      app:
        controller: zwave-js-ui
        ports:
          http:
            port: *port
          websocket:
            port: 3000
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: zwave-js-ui.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - zwave-js-ui.${DOMAIN}
            secretName: zwave-js-ui-certificate-secret
    persistence:
      config:
        existingClaim: zwave-js-ui-config-volume
        globalMounts:
          - path: /usr/src/app/store
      tmp:
        type: emptyDir
      usb:
        type: hostPath
        hostPath: /dev/zwave
        #hostPathType: CharDevice
        globalMounts:
          - path: /dev/zwave