apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: openwebui-config-volume
    namespace: ai
    labels:
      app: openwebui
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi