apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: flux-system
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:YggWr6XYihh7sdG9MtipTMxTVsUh0PN+x5Y1KdrU360=,iv:Q4M1D2foeJ+bX/uQlUNGw0NxZv16vzUCUrmSr+ACJOs=,tag:fnBZt0cFQ86XzldKeneN3w==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-01T15:32:41Z"
    mac: ENC[AES256_GCM,data:ewVYSxqt63PoSitx2I3tPe/2N+Ok8JVpBlp6j9roll+S8Hz5HIEOVzIUTih/REt6bhxFC6P0E2WR6pAKKdFd3Cbn9+PebixaBHJw/v/dyP3tSHizu2HFjfTNVbF3CfNDpVYF6gTKjuqB1l2PFIza6pJrfcRjsruFaor7ltf2Fts=,iv:9Oc5+epJKPgT5N/z4R3FGTdU88Tp8o2/iaXfECv2Lcs=,tag:DQiCd/yCVUrlmah0oLHfMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
