apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn-system
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-system
        namespace: longhorn-system
      interval: 6h