apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets-charts
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: ghcr.io/external-secrets/external-secrets
    bitwarden-sdk-server:
      enabled: false
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
    installCRDs: true
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m