apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  data:
  - secretKey: test_secret
    remoteRef:
      key: test_secret
  - secretKey: test_secret_2
    remoteRef:
      key: test_secret_2