apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: find-by-tags
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  dataFrom:
  - find:
      name:
        regexp: "test"