apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  data:
  - secretKey: test
    remoteRef:
      key: "bf18e694-3892-4c24-8130-b2da012e127d"