apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-ingress-certificate
  namespace: web
spec:
  secretName: homepage-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - ${DOMAIN}