apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      homepage:
        serviceAccount:
          identifier: homepage
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.2.0@sha256:5e6bcbb595c4e857540577135e0f8b3ffc2e97c23d6e0ddc7df183de5bfdd442
            env:
              TZ: America/Denver
              HOMEPAGE_ALLOWED_HOSTS: homepage.k3s.ravenholm.io
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 20m
                memory: 200Mi
              limits:
                memory: 1Gi
            envFrom:
              - secretRef:
                  name: homepage-secrets
    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: homepage.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - homepage.k3s.ravenholm.io
            secretName: homepage-certificate-secret
    serviceAccount:
      homepage: {}
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
          - subPath: custom.css
            path: /app/config/custom.css
          - subPath: favicon.png
            path: /app/public/images/favicon.png