apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./certificate.yaml
  - ./rbac.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: homepage-config
    namespace: web
    files:
      - bookmarks.yaml=./resources/bookmarks.yaml
      - docker.yaml=./resources/docker.yaml
      - kubernetes.yaml=./resources/kubernetes.yaml
      - services.yaml=./resources/services.yaml
      - settings.yaml=./resources/settings.yaml
      - widgets.yaml=./resources/widgets.yaml
      - custom.css=./resources/custom.css
generatorOptions:
  disableNameSuffixHash: true