apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: flux-system
stringData:
    SECRET_JELLYFIN_API_KEY: ENC[AES256_GCM,data:COrsOlSHwzXLY1cAaSzLlxiUn0yzXkzcdLi29gRg2zQ=,iv:aXxAJ36+W7lpt1ca4l+4davsVtF+7uUC7SjNMwnXrB4=,tag:k1RBeDm/OaNPeTldDjIyBQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T21:28:13Z"
    mac: ENC[AES256_GCM,data:Fv2hdr7udlhO0fodcg4iJs3HEoQMC8PxCgHAvU3QVim4Q6Rc9h28b7y52zJgdGbEDbzeD/koTIAQrq8ZM8FETP+RebbGb9YsS4rl4JlNvJVBr8NJposALVAr4mXVYtQRZynAg+HgB/q4DkNPSBtGeIqE38RVAq+v3KR2e+/hn70=,iv:IOpncMy9Q2vc/ladmySRY6GkaAvXJJwAunZiRZFogDs=,tag:Xfc1UJjxuANLFYn6XlpbaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
