---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-data
    namespace: networking
    labels:
      app: adguard-home
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-conf
    namespace: networking
    labels:
      app: adguard-home
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-work
    namespace: networking
    labels:
      app: adguard-home
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi
---