apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: adguard-home-config-volume
    namespace: media
    labels:
      app: adguard-home
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi