apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      adguard-home:
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.61
            env:
              TZ: America/Denver
    service:
      app:
        controller: adguard-home
        ports:
          http:
            primary: true
            port: 3000
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: adguard-home.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - adguard-home.k3s.ravenholm.io
            secretName: adguard-home-certificate-secret
    persistence:
      data:
        enabled: true
        existingClaim: adguard-home-config-volume
        subPath:
          - path: conf
            mountPath: /opt/adguardhome/conf
          - path: data
            mountPath: /opt/adguardhome/work