apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: monitor
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./cluster/apps/monitor/kube-prometheus-stack/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m