apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nzbget-ingress-certificate
  namespace: media
spec:
  secretName: nzbget-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - nzbget.k3s.ravenholm.io