apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
    controllers:
      nzbget:
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/nzbget
              tag: v21.1-ls136
            resources:
              requests:
                cpu: 200m
                memory: 500Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: nzbget
        ports:
          http:
            port: 6789
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: nzbget.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - nzbget.${DOMAIN}
            secretName: nzbget-certificate-secret
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-volume
      downloads:
        type: nfs
        server: ${FS1_IP}
        path: ${DOWNLOADS_PATH}
        globalMounts:
          - path: /downloads
