apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: calibre-web-automated-config-volume
    namespace: media
    labels:
      app: calibre-web-automated
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi