---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: calibre-web-automated
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      calibre-web-automated:
        pod:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: V3.1.4@sha256:577e846f104fd21453ef306eefb4a95dd95b3b9ddd2463a150944494284da0fd
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /login
                    port: &port 8083
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                add:
                  # S6
                  - CHOWN
                  - SETUID
                  - SETGID
                  - FOWNER
                  - DAC_OVERRIDE
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      app:
        controller: calibre-web-automated
        ports:
          http:
            port: *port
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: cwa.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - cwa.${DOMAIN}
            secretName: calibre-web-automated-certificate-secret
    persistence:
      config:
        existingClaim: calibre-web-automated-config-volume
      cache:
        type: emptyDir
      media:
        type: nfs
        server: ${FS1_IP}
        path: ${BOOKS_PATH}
        globalMounts:
          - path: /cwa-book-ingest
            subPath: Downloads/Books
          - path: /calibre-library
            subPath: Books
      tmp:
        type: emptyDir