apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: sonarr
        namespace: sonarr
      interval: 6h