apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitor
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.0.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.monitor.svc.cluster.local
          access: proxy