apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntarr-ingress-certificate
  namespace: media
spec:
  secretName: huntarr-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - huntarr.${DOMAIN}