apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: huntarr-config-volume
    namespace: media
    labels:
      app: huntarr
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi