apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mkdocs-ingress-certificate
  namespace: web
spec:
  secretName: mkdocs-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - mkdocs.${DOMAIN}