apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mkdocs-docs-volume
    namespace: web
    labels:
      app: mkdocs
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 50Mi