apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mkdocs
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mkdocs:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: squidfunk/mkdocs-material
              tag: latest
    service:
      app:
        controller: mkdocs
        ports:
          http:
            port: 8000
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: mkdocs.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - mkdocs.${DOMAIN}
            secretName: mkdocs-certificate-secret
    persistence:
      #data:
        #type: nfs
        #server: ${FS1_IP}
        #path: /mnt/zpool2/other/mkdocs
        #globalMounts:
          #- path: /docs
      config:
        type: configMap
        name: mkdocs-config
        globalMounts:
          - subPath: mkdocs.yml
            path: /docs/mkdocs.yml
      data:
        type: configMap
        name: mkdocs-main
        globalMounts:
          - subPath: test.md
            path: /docs/main/test.md
      