apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mkdocs
  namespace: web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mkdocs:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: squidfunk/mkdocs-material
              tag: latest
    service:
      app:
        controller: mkdocs
        ports:
          http:
            port: 8000
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: mkdocs.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - mkdocs.k3s.ravenholm.io
            secretName: mkdocs-certificate-secret
    persistence:
      data:
        type: nfs
        server: 10.0.0.20
        path: /mnt/zpool2/other/mkdocs
        globalMounts:
          - path: /docs-dir
      config:
        type: configMap
        name: mkdocs-config
        globalMounts:
          - subPath: mkdocs.yml
            path: /docs/mkdocs.yml
      test:
        type: emptyDir
        path: /temp