apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./certificate.yaml
  - ./docs-pvc.yaml
configMapGenerator:
  - name: mkdocs-config
    namespace: web
    files:
      - mkdocs.yml=./resources/mkdocs.yml
generatorOptions:
  disableNameSuffixHash: true