apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./certificate.yaml
configMapGenerator:
  - name: mkdocs-config
    namespace: web
    files:
      - mkdocs.yml=./resources/mkdocs.yml
  - name: mkdocs-docs
    namespace: web
    files:
      - test.md=./resources/docs/test.md
generatorOptions:
  disableNameSuffixHash: true