apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: frigate-config-volume
    namespace: home
    labels:
      app: frigate
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi