apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./certificate.yaml
configMapGenerator:
  - name: frigate-configmap
    namespace: home
    files:
      - config.yml=./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
