apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wg-easy-ingress-certificate
  namespace: networking
spec:
  secretName: wg-easy-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - vpn.${DOMAIN}