apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wg-easy-config-volume
    namespace: networking
    labels:
      app: wg-easy
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi