apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wg-easy:
        pod:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            seccompProfile: { type: RuntimeDefault }
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/wg-easy/wg-easy
              tag: 14@sha256:66352ccb4b5095992550aa567df5118a5152b6ed31be34b0a8e118a3c3a35bf5
            env:
              LANG: en
              WG_HOST: vpn.${DOMAIN}
              WG_DEFAULT_ADDRESS: 10.10.0.x
              WG_DEFAULT_DNS: 10.0.0.1
              WG_ALLOWED_IPS: 10.0.0.0/24
              UI_TRAFFIC_STATS: true
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_BIND_SERVICE
                  # - SYS_MODULE
                  - NET_RAW
                drop:
                  - ALL
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: wg-easy
        ports:
          http:
            port: 51821
        type: ClusterIP
      wg:
        controller: wg-easy
        ports:
          wg:
            port: 51820
            protocol: UDP
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: vpn.${DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: 51821
        tls:
          - hosts:
            - vpn.${DOMAIN}
            secretName: wg-easy-certificate-secret
    persistence:
      config:
        enabled: true
        existingClaim: wg-easy-config-volume
        globalMounts:
          - path: /etc/wireguard