apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: 17.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    service:
      vpn:
        type: LoadBalancer
        annotations:
          kube-vip.io/loadbalancerIPs: 10.0.0.177
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        integrations:
          traefik:
            enabled: false
        hosts:
          - host: wg-easy.${DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - wg-easy.${DOMAIN}
            secretName: wg-easy-certificate-secret
    persistence:
      config:
        existingClaim: wg-easy-config-volume
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOST: "0.0.0.0"
                PORT: "{{ .Values.service.main.ports.main.port }}"
                INSECURE: false