ports:
  dns: 53
  http: 4000
upstreams:
  groups:
    default:
      - 10.0.0.1
filtering:
  queryTypes:
    - AAAA
blocking:
  denylists:
    hagezi:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif.medium.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh.txt
  clientGroupsBlock:
    default:
      - hagezi
  loading:
    refreshPeriod: 6h
    concurrency: 1
    downloads:
      timeout: 10m
      cooldown: 10s
prometheus:
  enable: true
caching:
  maxItemsCount: 10_000
  prefetching: true
  prefetchMaxItemsCount: 1_000
  cacheTimeNegative: 30s