apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 34.4.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 6h