---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/component: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    app.kubernetes.io/component: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    app.kubernetes.io/component: media
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/component: networking
---
apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    app.kubernetes.io/component: monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: home
  labels:
    app.kubernetes.io/component: home
---