apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-ingress-certificate
  namespace: media
spec:
  secretName: jellyfin-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - jellyfin.k3s.ravenholm.io