apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jellyfin-config-volume
    namespace: media
    labels:
      app: jellyfin
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 10Gi