apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 6h
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 100
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.14@sha256:acd5416ab9c36d017687820a32f09d09a4e25a5754aa5ebeae2e7c63d7609c13
              pullPolicy: IfNotPresent
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-volume
        type: persistentVolumeClaim
