apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-ingress-certificate
  namespace: media
spec:
  secretName: sonarr-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - sonarr.${DOMAIN}