apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: recyclarr-config-volume
    namespace: media
    labels:
      app: recyclarr
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi