apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: flux-system
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:FqPHEQg90qHajd+G0oRUhBsfSJAuLcYktyNjAmdbonY=,iv:BEroFc/jYpQhFwfXS/7gi2Qx5SOJi5zcjSJ2DcEumjU=,tag:Zza/r2tCGCjqw0noPOPtRg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:3WL8s7hiS3Fx/ooShN4vF5p2LKZoUwofvp7VKwGcgWk=,iv:s32rkqfu75DsXd9DdGQKSoP4juagFAL0Yx3UT76AF+U=,tag:FOuY8t0aUyjYn83PH2LhaQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T02:17:50Z"
    mac: ENC[AES256_GCM,data:K6HwjBGpV7ERNRzAP2ghjBtTjnX1w0+SduRPifn7guUuMX2Ck22MWokfQDOcbSUYbX5OlGpP0dfGHsuPLe/KahTPj/IhY2CTh/m5DYz6JAL95ilRsrt57fltMNu91w12CAgKK6IYHEVdddPIC0LL1krZ5MdOT0NRMVsm/GLSKg4=,iv:M7rZp8gQPKUFVI9GjOOMwITpcIz54H8r4qbfbfJLcPo=,tag:6lXDN8WBkvjjfOEneUZGMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
