apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:DJadSGDWsZbv5wNSzvnswQ==,iv:RuuAR7VKQdqH9IDS7pN4RhfIW9JBFAW7c1L+H9xpZzU=,tag:hs8hGL6VC0bat+6NWL63FQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T14:45:02Z"
    mac: ENC[AES256_GCM,data:7yhzODpk7wdxif4R+s8iLMeymMb/3BJsMzRNMFnSmVIEK+0XHnxRwm7NM8ghj3WN1HYYVwUHLrL6tAjmwfVtErKGdbcF3TD+OeW57Pj1wUQbx3OeAJsiHRPlkahF0u61mjBECFAGb+zoPxeHIxaGhQEPBEWZpvylj+/akTNKTwQ=,iv:kWFzHFml62WQk52RzELrgIjdbDO3HxK2EYsIxwC5JtA=,tag:WmxEI704z9EQ4smjQyaBGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
