apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN: ENC[AES256_GCM,data:Z82iZprSi9QoinlZ,iv:EkvkNcTiCtin3zgI7jB+KJnL/J/v4ved4gCi72h2ggY=,tag:PYTxXjWLwkQPRE8P31veOw==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T17:27:59Z"
    mac: ENC[AES256_GCM,data:SRQbw0ieDzKrmbGf+LqX/jZ2+rLQ5QT3niM9RD1LUkfj/kAZniD0GFBR/i3PkMH03M9MxBsAvYbq+kWc93Eng+MUzMwhBQOFiG4tGgCh+bhrBr/BU9HkdqGfhY0I50e7GvXJJfyPi8SwEQB8j6M5W3diUA5xyCnAqtNJNrVT7Bs=,iv:91CAzRylnHeVM7z/nzhNla2EEoITuvxl38EdQUftNRM=,tag:Rga9kKBmIkqhI7dIyXeZFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
