apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ND_SPOTIFY_ID: ENC[AES256_GCM,data:kIx3ynUAMUGNYrPCZJgsCukBEqTnpPtDDuDorbpcXBM=,iv:0jc1Vltdy9sLsCjoMGR3xGxiHTWhguXaV2vNC3+6gsQ=,tag:i4sFgUjwzGqMy5x6wyaHUA==,type:str]
    SECRET_ND_SPOTIFY_SECRET: ENC[AES256_GCM,data:8lTf9O4s3kbFtEIrsY/lAWuNvyPcq71mCD/y+3lKF5E=,iv:0JxUCbVuSjdUiW4jPV4f4n4LVcpPHcbvuQQCbpMwlAc=,tag:bF/tKIfHIkuco+RRa6qE7w==,type:str]
    SECRET_ND_LASTFM_APIKEY: ENC[AES256_GCM,data:9V7bMYXmb3BOl22yLGrouzbFXc0OyI30yhBNE3GHDW0=,iv:FUVqd9ao2j7gAjXCj/3CuLBd42q3VZz/lbxdLVxeg6s=,tag:vWkgrnpqEOxBBzxtkHvy/A==,type:str]
    SECRET_ND_LASTFM_SECRET: ENC[AES256_GCM,data:tJOTTptOujrm96QV+n6K+PEKHD9vA5iqkKO6c8iLPwY=,iv:B7GVSjzAdPVZCJ/+zgDaqGh8HsqiplS569L33h3/TAs=,tag:YXBraAN0rdC7QM1JGxzEAQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T23:36:26Z"
    mac: ENC[AES256_GCM,data:CSjU4ftIFBqSQvjINjuOz5cA0cJYtCVHBb7wWGW2u9+46WyoLYSAJE82UeTckcCKO67eZ2flmlKkh1zk1c1KEZGndZc+meE6jpsAeoc8tcFVFHZJks3zUgzR/UfHszlMGMQ79lmbCSP382jjV2nhrYP/Rgiktk08BtdVaAkuDMg=,iv:3EfcyWuDP8owW0751sqmm94++PoE35gU0oXpDMyheA8=,tag:9c5xnJWevceaVmGcbJ5YXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
