apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TEST_USER: ENC[AES256_GCM,data:EVCvZg==,iv:eiu78Q08GSilcdlW5O4hiKLQ2tqqNjWIrsKbnFKTXS0=,tag:Ii0hMKmCVcKpdffEvgm10g==,type:str]
    TEST_PASS: ENC[AES256_GCM,data:GsRMTeopr2Y=,iv:d6/PGe6To5YUlkja0LmdoLHTaSi5VlwbqvlaZON392w=,tag:hsN5vRtWCnqunnzbRjEOOw==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T20:13:57Z"
    mac: ENC[AES256_GCM,data:wmvRXOY//c7A1E2Ato/LQkL+GEZQsXAWhfWOJ5xjq76uLHG8TsSp/lpmgVrmCrZ3MPs9n6N62iLIDUUiM1DVMmT0HVUJW7vaomaVJBF7XCq4jqhCJknngBAbnpVPfA6XKozfIpno9On268dPMqMG0jFaSOcy9/zcld6/vHJWcc0=,iv:78K31Av8XSqpLXWh2QTBAAKtq8jj7c+93gzpTFqM84U=,tag:l5cCX5665KXxg//eRWT0qg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
