apiVersion: ENC[AES256_GCM,data:n0E=,iv:NvY4ZOTtTpIPpoCkLcugd7BMOZCFqMaGi8qTwyiDJ1c=,tag:Z4r/TQDMdc7JfJb8OZfA1g==,type:str]
kind: ENC[AES256_GCM,data:dQ15Abcn,iv:OLMtG5BBtGhq6wBz3koJ5F5X7kRdyYBNMmhRQKdpD5I=,tag:O+DP+vAo7MGDK/PECCRi8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vd7ga8zdFoN4,iv:fwmNu510yT45TqhO6fSf96qs8FCTAaX39CjvEswRlxE=,tag:hrTJ3zfUk0AeO4uspofUoA==,type:str]
    namespace: ENC[AES256_GCM,data:ASKv1jKhAA==,iv:XKXCqimp/7dqMAQTmO76MDsyhqoCQc7+SEl39UXQ6Vg=,tag:PhHaMi9X6F2n5SD8jxSrSA==,type:str]
stringData:
    TEST_USER: ENC[AES256_GCM,data:rnE2tQ==,iv:XXSCTg0jt8djq45FSX3SljmEvJdBoS/61vmri8dDGr8=,tag:m+l4KQrFCYrzOUmagFIIPw==,type:str]
    TEST_PASS: ENC[AES256_GCM,data:yfXM9iTyhHc=,iv:WqARAfhy813RCPi2os6+wGEF/c3+NeIg5/Q03biGBRY=,tag:RRYmT9xopaugdMsiu4arHw==,type:str]
    OTHER: ENC[AES256_GCM,data:x+aLMw==,iv:fUw02cqXIbDfO36Zs+Y1H/8+eV3l7Ccf/l67jSt/sd0=,tag:bxAdR252lRcbjHSKKndytQ==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNCtZQXo4ejlXckJPbzF5
            bGZaZFFiZ1ZoTEJ6NlhZMDBQY3NGeldlZUg0CjUwT3RzNDRadXVKbUR5Sm8xYlR5
            WlZiUmsrcTlNQzR5MUhVR2VGOG9ZalUKLS0tIGQ3ZTFOVWhxZGVuWE42Z1FkOXVq
            dWNZYTlOV0dTTnBMMlpJa3AwYnY2QUkKTMBnBS3Q6pT1pGF6VbQEvzqmY11NDYPC
            EVZHe0cNh0FYBEcEdMs0NROlGv+XJVn8mEAFkaY3SGWmD8No9rmLjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T18:15:48Z"
    mac: ENC[AES256_GCM,data:cxvGYyyt7c8a9jxyLuanVcjc/50cPtaW86bewkRiB4HetwP8eXJsXs6ZXN6faoaC+sI1dHsb2u4HXPsB91JSboR2PWVe0i9K6Wu+ThVC53qurhi7+gseX6cKGNoXmIjLtvvUULsIQ4hgiC5BjEsUo0qhwPpjVnjWT6XoT/4qOXo=,iv:4tZu9Leb/Bh51d2t+Gh9kmkcuuQARe1H5LbGiJgYqps=,tag:2+drwpWp8+9Sf3qTF1bpiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
