apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: flux-system
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:tpDAOMNi9wqRovdtuOXrINC3rCA+tw0/dV3o9gHYhWpgR+TBn9ZXuQ==,iv:f+coQWeKxqlOFI/n9uLc6Iph08V6izb4svNxRZg5oMw=,tag:Asbukl8n+75Rdnj1v5/KDg==,type:str]
sops:
    age:
        - recipient: age17wezhckaqyhyxud66fq5ckra06h3837p4uzqemymn9cjspq9eshq0eyf0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESi9Zem1NNlBRbFpRTHZZ
            L2RvNWZaKzNRMmFqeUdWOEFHd3pzeTVMYkdFClp6OUdxRUU3Q1lINWJneDVpency
            dkVIZ2ZHbndFVHFPTHJ6SEYrdlBmOFEKLS0tIFFkTXgvRVJLY3JMRm94RkhpQVBw
            SENwTm0vYXNJdVVlOUJISlRqM1hWZW8KJ8qaTTTSEghg99/SI86OPAtL1jlSN5sJ
            Hu2KoB8nZFodZEEHmM7IWOH/Vno8nwbeMqhuRnnVv5Qqo9Sn6hPIPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T16:58:11Z"
    mac: ENC[AES256_GCM,data:k43okK2xygT6Xr24OkK/KQ69BS4DVYe2Y/6C77dmv9CeW0aYUCnUqjhV+Djj4I+FVQBSfFGVSsJ6mbndv8HK+/CLqse9Yn++lkFDrK5mBQqAi8wWYF7JSWtd7owQ72ly5KtCeBTeyP2vgGq6CMvkFEsNlg4Nn7mTOyaGqiUvAxU=,iv:Vr4J+dMZNM7yErFjxwmduWbeTx8justV2tZx/50xvwg=,tag:dV6GdRfH1eMC9qUKi9zZIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
