apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-ingress-certificate
  namespace: home
spec:
  secretName: home-assistant-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - home-assistant.k3s.ravenholm.io