apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: home-assistant-config-volume
    namespace: home
    labels:
      app: home-assistant
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi