apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.5.1@sha256:020eecfb33fbc8473a54d24607e0352d4381af51d9963cfa70b7b915115da2d1
            env:
              HOME_ASSISTANT_EXTERNAL_URL: https://home-assistant.k3s.ravenholm.io
              HOME_ASSISTANT_PURGE_KEEP_DAYS: 30
              HOME_ASSISTANT_TRUSTED_PROXIES: 10.0.0.0/8
              HOME_ASSISTANT_UNIT_SYSTEM: us_customary
              TZ: America/Denver
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 1Gi
    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: home-assistant.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - home-assistant.k3s.ravenholm.io
            secretName: home-assistant-certificate-secret
    persistence:
      config:
        existingClaim: home-assistant-config-volume
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tts:
        type: emptyDir
        globalMounts:
          - path: /config/tts
      tmp:
        type: emptyDir