apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
    - name: google.coral
      labels:
        feature.node.kubernetes.io/custom-google-coral: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["1a6e"] }
            device: { op: In, value: ["089a"] }