apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-ingress-certificate
  namespace: media
spec:
  secretName: prowlarr-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - prowlarr.${DOMAIN}