apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-certificate
  namespace: nginx
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: nginx.staging.ravenholm.io