apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  fsType: "ext4"
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"