apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-vol
  namespace: media
spec:
  storageClassName: longhorn
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi