apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  storageClassName: ""
  volumeName: downloads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi