---
- Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.k3s.ravenholm.io
            description: Media Server
            widget:
              type: jellyfin
              url: http://jellyfin.media.svc.cluster.local:8096
              key: {{SECRET_JELLYFIN_API_KEY}}
              enableNowPlaying: true