---
- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: https://jellyfin.k3s.ravenholm.io
      description: Media Server
  - Radarr:
      icon: radarr.png
      href: https://radarr.k3s.ravenholm.io
      description: Movies Management
  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.k3s.ravenholm.io
      description: TV Shows Management
- Infrastructure:
  - TrueNAS:
      href: http://truenas
      icon: truenas.png
      description: TrueNAS Scale
      widget:
        type: truenas
        url: http://truenas
  - Proxmox:
      href: https://10.0.0.30:8006
      icon: https://www.45drives.com/solutions/proxmox/img/proxmox_Logo.png
      description: Virtualization Platform
      widget:
        type: proxmox
        url: https://10.0.0.30:8006