---
- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: https://jellyfin.k3s.ravenholm.io
      description: Media Server
      statusStyle: "dot"
  - Navidrome:
      icon: navidrome.png
      href: https://navidrome.k3s.ravenholm.io
      description: Audio Server
      statusStyle: "dot"
  - Radarr:
      icon: radarr.png
      href: https://radarr.k3s.ravenholm.io
      description: Movies Management
      statusStyle: "dot"
  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.k3s.ravenholm.io
      description: TV Shows Management
      statusStyle: "dot"
  - Lidarr:
      icon: lidarr.png
      href: https://lidarr.k3s.ravenholm.io
      description: Audio Management
      statusStyle: "dot"
  - Prowlarr:
      icon: prowlarr.png
      href: https://prowlarr.k3s.ravenholm.io
      description: Index Management
      statusStyle: "dot"
  - Jellyseer:
      icon: jellyseer.png
      href: https://jellyseer.k3s.ravenholm.io
      description: Media Requester
      statusStyle: "dot"
- Home:
  - Homeassistant:
        icon: homeassistant.png
        href: https://home-assistant.k3s.ravenholm.io
        description: Home Automation
        statusStyle: "dot"
  - Frigate:
        icon: frigate.png
        href: https://frigate.k3s.ravenholm.io
        description: Security Camera NVR
        statusStyle: "dot"
- Infrastructure:
  - TrueNAS:
      href: http://truenas
      icon: truenas.png
      description: TrueNAS Scale
  - Proxmox:
      href: https://10.0.0.30:8006
      icon: https://www.45drives.com/solutions/proxmox/img/proxmox_Logo.png
      description: Virtualization Platform
  - Unifi:
      href: https://10.0.0.1
      icon: unifi.png
      description: Network Management