---
- Media:
  - Jellyfin:
      icon: jellyfin.png
      href: https://jellyfin.ravenholm.io
      description: Movie & TV Show Streaming
      siteMonitor: http://jellyfin.media.svc.cluster.local:8096
      statusStyle: "dot"
  - Navidrome:
      icon: navidrome.png
      href: https://navidrome.ravenholm.io
      description: Audio Streaming
      siteMonitor: http://navidrome.media.svc.cluster.local:4533
      statusStyle: "dot"
  - Radarr:
      icon: radarr.png
      href: https://radarr.ravenholm.io
      description: Movie Management
      siteMonitor: http://radarr.media.svc.cluster.local:7878
      statusStyle: "dot"
  - Sonarr:
      icon: sonarr.png
      href: https://sonarr.ravenholm.io
      description: TV Show Management
      siteMonitor: http://sonarr.media.svc.cluster.local:8989
      statusStyle: "dot"
  - Lidarr:
      icon: lidarr.png
      href: https://lidarr.ravenholm.io
      description: Audio Management
      siteMonitor: http://lidarr.media.svc.cluster.local:8686
      statusStyle: "dot"
  - Prowlarr:
      icon: prowlarr.png
      href: https://prowlarr.ravenholm.io
      description: Index Management
      siteMonitor: http://prowlarr.media.svc.cluster.local:9696
      statusStyle: "dot"
  - Jellyseerr:
      icon: jellyseerr.png
      href: https://jellyseerr.ravenholm.io
      description: Movie & TV Show Requester
      siteMonitor: http://jellyseerr.media.svc.cluster.local:5055
      statusStyle: "dot"
- Home:
  - Home Assistant:
        icon: home-assistant.png
        href: https://home-assistant.ravenholm.io
        description: Home Automation
        siteMonitor: http://home-assistant.home.svc.cluster.local:8123
        statusStyle: "dot"
  - Frigate:
        icon: frigate.png
        href: https://frigate.ravenholm.io
        description: Security Camera NVR
        siteMonitor: http://frigate.home.svc.cluster.local:5000
        statusStyle: "dot"
  - Z-Wave JS UI:
        icon: z-wave-js-ui.png
        href: https://zwave-js-ui.ravenholm.io
        description: Z-Wave Device Management
        siteMonitor: http://zwave-js-ui.home.svc.cluster.local:8091
        statusStyle: "dot"
- Utilities:
  - Grafana:
      href: https://grafana.ravenholm.io
      icon: grafana.png
      description: Logs & Metrics
  - MkDocs:
      href: https://mkdocs.ravenholm.io
      icon: mkdocs.png
      description: Notes & Documention
  - NZBGet:
      href: https://nzbget.ravenholm.io
      icon: nzbget.png
      description: Usenet Downloader
- Infrastructure:
  - Proxmox:
      href: https://10.0.0.30:8006
      icon: https://www.45drives.com/solutions/proxmox/img/proxmox_Logo.png
      description: Virtualization Platform
  - TrueNAS Fast:
      href: http://10.0.0.10
      icon: truenas.png
      description: Flash Storage
  - TrueNAS Slow:
      href: http://10.0.0.20
      icon: truenas.png
      description: Archive Storage
  - Longhorn:
      href: https://longhorn.ravenholm.io
      icon: longhorn.png
      description: Cluster Storage
- Networking:
  - Unifi:
      href: https://10.0.0.1
      icon: unifi.png
      description: Network Management
  - Wireguard:
      href: https://wg-easy.ravenholm.io
      icon: wireguard.png
      description: VPN Management