---
title: Ravenholm
favicon: https://www.google.com/favicon.ico
background:
  image: https://backiee.com/static/wallpapers/560x315/376789.jpg
  blur: 2xl # https://tailwindcss.com/docs/backdrop-blur
  brightness: 50
theme: dark
color: slate
headerStyle: clean
hideVersion: true
disableCollapse: true
layout:
  Media:
    style: row
    columns: 4
  Home:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4