---
title: Ravenholm
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
theme: dark
color: slate
headerStyle: clean
hideVersion: true
disableCollapse: true
layout:
  Media:
    style: row
    columns: 4
    icon: mdi-play-circle
  Home:
    style: row
    columns: 4
    icon: mdi-home
  Infrastructure:
    style: row
    columns: 4
    icon: mdi-server