---
title: Ravenholm
favicon: https://www.google.com/favicon.ico
background:
  image: https://c4.wallpaperflare.com/wallpaper/276/478/552/video-game-garry-s-mod-wallpaper-preview.jpg
  blur: md # https://tailwindcss.com/docs/backdrop-blur
  brightness: 50
theme: dark
color: slate
headerStyle: clean
hideVersion: true
disableCollapse: true
layout:
  Media:
    style: row
    columns: 4
  Home:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4