---
title: Ravenholm
favicon: https://www.google.com/favicon.ico
background:
  image: https://preview.redd.it/1920x1080-bleakwatch-crossing-dark-fantasy-style-v0-tfmc2mv7hugc1.jpeg?auto=webp&s=06d47c042931cb42b627c969f090e52878748007
  blur: xl # https://tailwindcss.com/docs/backdrop-blur
  brightness: 50
theme: dark
color: slate
headerStyle: clean
hideVersion: true
disableCollapse: true
layout:
  Media:
    style: row
    columns: 4
  Home:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 4