apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-red-ingress-certificate
  namespace: home
spec:
  secretName: node-red-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - node-red.${DOMAIN}