apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: node-red-config-volume
    namespace: home
    labels:
      app: node-red
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi