apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
configMapGenerator:
  - name: blocky
    namespace: networking
    files:
      - ./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true