apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - jetstack.yaml
  - traefik.yaml
  - bjw-s.yaml
  - node-feature-discovery.yaml
  - intel.yaml
  - grafana.yaml
  - prometheus-community.yaml
  - bitwarden.yaml