---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: default
spec:
  interval: 30m
  url: oci://ghcr.io/traefik/helm/traefik
  timeout: 3m
  type: oci