apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zwave-js-ui
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  path: ./cluster/apps/home/zwave-js-ui/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m