apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mosquitto-config-volume
    namespace: home
    labels:
      app: mosquitto
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: longhorn
    resources:
        requests:
            storage: 1Gi