apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.20
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: mosquitto
        ports:
          http:
            port: 80
            enabled: false
          mqtt:
            port: 1883
            enabled: true
        type: ClusterIP
    ingress:
      app:
        className: traefik
        hosts:
          - host: mosquitto.k3s.ravenholm.io
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - mosquitto.k3s.ravenholm.io
            secretName: mosquitto-certificate-secret
    persistence:
      config:
        existingClaim: mosquitto-config-volume
        globalMounts:
          - path: /config