apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.20
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: mosquitto
        ports:
          mqtt:
            port: 1883
            enabled: true
        type: ClusterIP
    persistence:
      config:
        existingClaim: mosquitto-config-volume
        globalMounts:
          - path: /config
      config-file:
        enabled: true
        type: configMap
        name: mosquitto-configmap
        advancedMounts:
          mosquitto:
            app:
              - path: /mosquitto/config/mosquitto.conf
                subPath: mosquitto.conf