apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-ingress-certificate
  namespace: media
spec:
  secretName: grafana-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - grafana.k3s.ravenholm.io