---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-service
spec:
  selector:
    app: longhorn-ui
  ports:
  - port: 3250
    targetPort: 80
  type: LoadBalancer
  annotations:
    "kube-vip.io/loadbalancerIPs": "10.0.0.110"