apiVersion: v1
kind: Service
metadata:
  name: longhorn-lb
  namespace: longhorn-system
spec:
  type: LoadBalancer
  selector:
    app: longhorn
  ports:
    - port: 8080
      targetPort: 80
  annotations:
    "kube-vip.io/loadbalancerIPs": "10.0.0.110"