apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-ingress-certificate
  namespace: web
spec:
  secretName: nginx-certificate-secret
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: 
    - nginx.k3s.ravenholm.io